kind: pipeline
type: kubernetes
name: default-exemple


######################################################   trigger
trigger:
  branch:
  - main
  when:
    event:
      exclude:
      - pull_request   


###################################################   build-push
steps:
- name: build-push
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run  
  privileged: true
  commands:
  - sleep 5 ## give docker enough time to start
  - docker login -u uzieljr -p zairaf00270027
  #- docker build  -t uzieljr/poc-site:latest .
  #- docker push uzieljr/poc-site:latest
  #get mensage commit to tag
  - docker build  -t uzieljr/poc-site:${DRONE_COMMIT_SHA:0:7} .
  - docker push uzieljr/poc-site:${DRONE_COMMIT_SHA:0:7}


######################################################   Delivery
- name: delivery
  image: sinlead/drone-kubectl
  #Ssettings:
    #kubernetes_server:
      #from_secret: k8s_server
    #kubernetes_cert:
      #from_secret: k8s_cert
    #kubernetes_token:
      #from_secret: k8s_token
  commands:
  - kubectl get namespace




########################################################   Services   
services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
volumes:
- name: dockersock
  temp: {}