kind: pipeline
type: docker
name: Build Image and Push

##########################################################
############################################   Start steps
##########################################################


steps:
##################################################   build
- name: build
  image: ubuntu
  pull: always
  commands:
  - go build
  - docker build -t .
  

################################################   publish
- name: publish
  image: done-build-image
  settings:
    username: uzieljr
    password: zairaf00270027
    repo: uzieljr/poc-site
    tags:
    - 1.0.0
    - 1.0

################################################   trigger
trigger:
  branch:
  - main
  when:
    event:
      exclude:
      - pull_request   

# # - name: notify
# #   image: plugins/slack
# #   settings:
# #     channel: developers
# #     username: drone
