kind: pipeline
type: docker
name: uzi-pipeline-poc

trigger:
  branch:
  - main


steps:
- name: backend
  image: golang
  commands:
  - go build
  - go test

- name: frontend
  image: node
  commands:
  - npm install
  - npm test